---
title: "NY NOAA Data Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
```

```{r load data and data cleaning}
data("ny_noaa")
ny_noaa <- ny_noaa %>%
  filter(!is.na(prcp), #remove missing values
         !is.na(tmax), 
         !is.na(tmin)) %>%
  mutate(
    tmax = as.numeric(tmax) / 10,  # convert from tenths of degrees C to degree C
    tmin = as.numeric(tmin) / 10,  # convert from tenths of degrees C to degree C
    prcp = as.numeric(prcp) / 10,  # convert from tenths of mm to mm
    year = lubridate::year(date), # extracts the year
    month = lubridate::month(date, label = TRUE, abbr = TRUE) # extracts the month
  )

# random sample the data
set.seed(42)
sample_data <- sample_n(ny_noaa, 500) 
```

-----------------------------------------------------------------------

### Chart A

```{r scatterplot}
scatter_plot <- sample_data %>%
  plot_ly(
    x = ~tmax, 
    y = ~prcp, 
    type = "scatter", 
    mode = "markers",
    color = ~tmax, 
    text = ~str_c("Date: ", date, "<br>Max Temp: ", tmax, "degree C", "<br>Precipitation: ", prcp, " mm"),
    alpha = 0.5
  ) %>%
  layout(
    title = "Scatterplot of Max Temperature vs Precipitation",
    xaxis = list(title = "Max Temperature (degree C)"),
    yaxis = list(title = "Precipitation (mm)")
  )
scatter_plot

```

-----------------------------------------------------------------------

### Chart B

```{r boxplot}
box_plot <- sample_data %>%
  plot_ly(
    x = ~month, 
    y = ~tmax, 
    type = "box", 
    color = ~month
  ) %>%
  layout(
    title = "Max Temperature Distribution by Month",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Max Temperature (°C)")
  )
box_plot
```

### Chart C

```{r bar chart}
bar_chart <- sample_data %>%
  group_by(month) %>%
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) %>%
  plot_ly(
    x = ~month, 
    y = ~avg_prcp, 
    type = "bar", 
    color = ~month
  ) %>%
  layout(
    title = "Average Precipitation by Month",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Average Precipitation (mm)")
  )
bar_chart
```